### ISSUE TITLE
stop poking with bs message in vscode plugin

### ISSUE THREAD

**Issue by kunthar** [bridgecrewio/checkov-vscode#119]
there is no cancel, stop, disable, blow up option on 
"Any troubles? We can help you figure out what happened" 
message of vscode plugin. 
let the user disable this unnecessary message please. 
put a counter counts to 3 and disable it if you like to. I will not slack you by this way!

<img width="500" alt="Screenshot 2022-12-26 at 9 39 55 PM" src="https://user-images.githubusercontent.com/49767/209576090-e6c80190-c7b4-46cf-93c2-a30cbb4829a0.png">

**Comment by kunthar** [comment]
Everytime this message pokes me, I will enter here! How is that.

**Comment by kunthar** [comment]
Again.

**Comment by kunthar** [comment]
And yet again.

**Comment by kunthar** [comment]
Again.

**Comment by SteveVaknin** [comment]
Hi @kunthar
You can set that in the extension settings, Look for `Disable Error Message` section and mark the checkbox to disable.
