### ISSUE TITLE
Checkov V3 and mandatory --repo-id

### ISSUE THREAD

**Issue by ultrajericho** [bridgecrewio/checkov-vscode#136]
Hello there,

As we migrated to Checkov V3 and the --repo-id argument has become mandatory, how can we set it in the extension ?
I can't have any code analysis anymore and it is blocking.

Regards,

**Comment by tsmithv11** [comment]
@ultrajericho we pushed a fix. In the meantime, you can pin the version of checkov to before 3.0

**Comment by ultrajericho** [comment]
Did you removed my last comment ? @tsmithv11

**Comment by tsmithv11** [comment]
@ultrajericho I didn't remove any comment. Are you talking about this one? https://github.com/bridgecrewio/checkov-vscode/pull/137#issuecomment-1783522037
