### ISSUE TITLE
VS Code Extension - Still installing/updating Checkov, please wait a few seconds and try again

### ISSUE THREAD

**Issue by AErmie** [bridgecrewio/checkov-vscode#28]
After installing and activating the extension (and also restarting VS Code), when I attempt to run the Checkov Scan command, I am presented with the following message: 

`"Still installing/updating Checkov, please wait a few seconds and try again." `

![Checkov-StillInstalling](https://user-images.githubusercontent.com/10376796/107130406-22eb5600-689b-11eb-99c7-83485b743ea7.png)

Is there a time-limit for activation? Is there anything else required aside from the steps listed in the [Configuration](https://github.com/bridgecrewio/checkov-vscode#configuration) section? 

I've tested this against the following VS Code versions... 

Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Version: 1.54.0-insider (user setup)
Commit: 52838cf6799cc448e738677ec37e86cf62a5bd89
Date: 2021-02-05T05:17:50.117Z
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by SteveVaknin** [comment]
Hi @AErmie, 
Can you please share with us your log file?

You can open the vscode Command Palette (Ctrl+Shift+P), run the command `Developer: Open Extensions Logs Folder`, and the log file should be inside the `Bridgecrew.checkov` folder.

**Comment by AErmie** [comment]
Here you go @SteveVaknin, sorry for the delay. 
[checkov.log](https://github.com/bridgecrewio/checkov-vscode/files/5940367/checkov.log)

**Comment by elaygl** [comment]
Resolved on version [v1.0.22](https://github.com/bridgecrewio/checkov-vscode/releases/tag/v1.0.22).

**Comment by alanwill** [comment]
I'm seeing this with version 1.0.30 that I just installed. Any thoughts on how to fix?

**Comment by VaskoBoshkov** [comment]
I'm seeing this with version 2.0.831 that i just installed.... And i have the same logs as @elaygl . Any solutions?

**Comment by bsweb** [comment]
I am seeing this in v1.0.88

**Comment by JonathanCrane-DOE** [comment]
I just saw this myself.
