### ISSUE TITLE
Use plugin without API access

### ISSUE THREAD

**Issue by jmhale** [bridgecrewio/checkov-vscode#39]
I'd like to use the Checkov VSCode plug-in from inside of a restricted environment, which would prevent me from allowing calls out to BC's API. However, the need for an API key seems to be a hard requirement. 

Can we have the API key be optional instead, knowing that we'll forego the fixes enrichment in the editor and just get violations feedback from the local `checkov` binary?

This seems like a similar use case to https://github.com/bridgecrewio/checkov/issues/759#issuecomment-780155903

Thanks!

**Comment by schosterbarak** [comment]
Hey @jmhale vscode extension is meant to be used by bridgecrew users. You can start using it for free https://bridgecrew.io/pricing/

I'm closing this issue for now.
