### ISSUE TITLE
Extension throws error for --repo-id when using Gitlab sub groups

### ISSUE THREAD

**Issue by schematis** [bridgecrewio/checkov-vscode#61]
With Gitlab you can have a structure that's  `group/subgroup/project` which causes the extension to throw an error as the extension expects `--repo-id` to have a structure of `group/project`.

**Comment by ceciliasharp** [comment]
simular problem for AzureDevoOps repo: https://[customer]@dev.azure.com/[customer]/[team]/
making it impossible to use the python setup for the extension.

**Comment by ceciliasharp** [comment]
may be fixed in https://github.com/bridgecrewio/checkov-vscode/pull/68
