### ISSUE TITLE
Space in Directory structure breaks checkov scan

### ISSUE THREAD

**Issue by Rices** [bridgecrewio/checkov-vscode#63]
Hi Bridgecrew Team,

I'm testing out the chevkov-vscode plugin on a Windows 10 Endpoint with VS Code and using CFNGoat. Checkov throws an exception when using the plugin and its scanning a file that contains a space in the directory structure:
![image](https://user-images.githubusercontent.com/5109530/130885199-93fb3bfd-653a-459b-9d24-f43cc366d5d1.png)

This issue can be fixed by encapsulating the cmdline argument in quotations e.g.
checkov -s --bc-api-key **** --repo-id bridgecrewio/cfngoat -f "c:\Users\XXX XXX\Documents\Bridgecrew\cfngoat\cfngoat.yaml" -o json 

Also - any future plans at this point to release an extension for Visual Studio?

**Comment by paulmowat** [comment]
I'll sort this one out as just encountered it as well while reviewing checkov.
