### ISSUE TITLE
v1.0.48 breaks Checkov run

### ISSUE THREAD

**Issue by jasonckeating** [bridgecrewio/checkov-vscode#70]
v1.0.48 breaks Checkov run, v1.0.47 still scans correctly

When scanning a file, Checkov fails with no problems listed.
The file has no issues, a CLI run shows all passing resources.

The previous version still works with no issues and gives a check mark

**Comment by SteveVaknin** [comment]
Hi @jasonckeating 
Can you please check if the issue still occurs?
Recently deployed changes that I might have fixed it

**Comment by jasonckeating** [comment]
@SteveVaknin just ran a few tests that were failing before.
This is fixed, thanks!
