### ISSUE TITLE
VS Code Extension - Still installing/updating Checkov, please wait a few seconds and try again

### ISSUE THREAD

**Issue by VaskoBoshkov** [bridgecrewio/checkov-vscode#89]
After installing and activating the extension (and also restarting VS Code), when I attempt to run the Checkov Scan command, I am presented with the following message:

"Still installing/updating Checkov, please wait a few seconds and try again."
[checkov.log](https://github.com/bridgecrewio/checkov-vscode/files/8056643/checkov.log)

I'm seeing this with version 2.0.831 that i just installed

**Comment by SteveVaknin** [comment]
Hi @VaskoBoshkov 
It looks like you failed to install checkov, we support `docker`, `pipenv` and `pip3`.

Do you have one of them installed? 
If so, is the executable accessible via CLI (saved in the `Path` env variable)?

**Comment by VaskoBoshkov** [comment]
Okay, I had some problems with pipenv, I've reinstalled and now it is working fine!

Thank you for your support!

**Comment by SteveVaknin** [comment]
Awesome, Thanks for the update!
